import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { createTextUpdates, parseTextUpdate, TEXT_PROMPT } from '../src/integrations/text-updates.js';
import { createMapTools } from '../src/integrations/tool-calling.js';
import { createDemoDocument } from '../src/core/demo.js';
import { createStore } from '../src/core/store.js';
import { createDraftSession } from '../src/core/draft.js';
import { bindChatStore } from '../src/adapters/chat.js';
import { preparePromptBook } from '../src/adapters/tool-lorebook.js';
const pause=()=>new Promise(resolve=>setTimeout(resolve,10));
function fixture(){
 const events=Object.fromEntries(['GENERATION_AFTER_COMMANDS','MESSAGE_RECEIVED','GENERATION_ENDED','GENERATION_STOPPED','CHAT_CHANGED'].map(k=>[k,k]));
 const source=new EventEmitter(),prompts=new Map(),registered=new Map();
 let ctx={characters:[{avatar:'a'}],characterId:0,getCurrentChatId:()=> 'a',chatMetadata:{},chat:[],extensionSettings:{},saveMetadata:async()=>{},saveSettingsDebounced(){},eventTypes:events,eventSource:source,setExtensionPrompt:(key,value)=>prompts.set(key,value),registerFunctionTool:t=>registered.set(t.name,t),unregisterFunctionTool:n=>registered.delete(n)};
 const store=createStore(createDemoDocument()),persistence=bindChatStore(store,{getContext:()=>ctx,storage:{getItem:()=>null,setItem(){}},namespace:'text'}),draft=createDraftSession(store,persistence),tools=createMapTools({store,draft,persistence,getContext:()=>ctx});
 persistence.importDocument(store.snapshot(),persistence.token());tools.configure({enabled:true,textMode:true});
 const reader=createTextUpdates({tools,getContext:()=>ctx});
 return {store,draft,tools,reader,ctx,source,registered,prompts,
  start(type='normal',params={},dry=false){source.emit(events.GENERATION_AFTER_COMMANDS,type,params,dry);const prompt=prompts.get('dynamic-map-text-update');return prompt?JSON.parse(prompt.split('本轮地图数据：\n')[1]):null;},
  reply(data,operations=[{op:'move',mapId:'world',id:'qingyun_sect'}]){const m={mes:'已经抵达。\n<map_update>'+JSON.stringify({token:data.token,reason:'已到达',operations})+'</map_update>',is_user:false,gen_finished:Date.now()};ctx.chat.push(m);return m;},
  async finish(reverse=false){const id=ctx.chat.length-1;if(reverse)source.emit(events.GENERATION_ENDED);source.emit(events.MESSAGE_RECEIVED,id);if(!reverse)source.emit(events.GENERATION_ENDED);await pause();},
  switch(){ctx={...ctx,chatMetadata:{},chat:[],getCurrentChatId:()=> 'b'};persistence.switchChat();source.emit(events.CHAT_CHANGED);},
  destroy(){reader.destroy();tools.destroy();draft.destroy();persistence.destroy();}
 };
}
test('text mode injects live IDs without native function calls, stages once in either host event order',async()=>{for(const reverse of [false,true]){const f=fixture();try{assert.equal(f.reader.status().supported,true);assert.equal(f.registered.get('dynamic_map_update').shouldRegister(),false);const data=f.start();assert.equal(data.map.currentLocation,'longmen_city');const m=f.reply(data);await f.finish(reverse);assert.equal(f.draft.snapshot().maps.world.currentLocation,'qingyun_sect');assert.equal(f.store.snapshot().maps.world.currentLocation,'longmen_city');const token=f.draft.token();await f.finish();assert.equal(f.draft.token(),token);assert.ok(m.mes.includes('<map_update>'));assert.equal(f.prompts.get('dynamic-map-text-update'),'');f.draft.save();assert.equal(f.store.snapshot().maps.world.currentLocation,'qingyun_sect');}finally{f.destroy();}}});
test('only completed assistant responses apply; partial, invalid, duplicate, historical and user text do not',async()=>{for(const kind of ['partial','invalid','duplicate','historical','user','system','unfinished','none']){const f=fixture();try{const data=f.start(),m=f.reply(data);if(kind==='partial')m.mes=m.mes.replace('</map_update>','');if(kind==='invalid')m.mes='<map_update>{bad}</map_update>';if(kind==='duplicate')m.mes+=m.mes;if(kind==='historical'){f.reader.reset();}if(kind==='user')m.is_user=true;if(kind==='system')m.is_system=true;if(kind==='unfinished')delete m.gen_finished;if(kind==='none')m.mes='继续聊天';await f.finish();assert.equal(f.draft.status().dirty,false,kind);}finally{f.destroy();}}});
test('streaming text is not applied before end, and stop after end cancels pending commit',async()=>{const f=fixture();try{f.reply(f.start());f.source.emit('MESSAGE_RECEIVED',0);await pause();assert.equal(f.draft.status().dirty,false);f.source.emit('GENERATION_ENDED');f.source.emit('GENERATION_STOPPED');await pause();assert.equal(f.draft.status().dirty,false);}finally{f.destroy();}});
test('aborted stream, caller abort, changed chat, changed draft and disabled mode reject late updates',async()=>{for(const kind of ['stream','abort','chat','draft','disabled','mode']){const f=fixture();try{const abort=new AbortController();f.reply(f.start('normal',{signal:abort.signal}));if(kind==='stream')f.ctx.streamingProcessor={isStopped:true};if(kind==='abort')abort.abort();if(kind==='chat')f.switch();if(kind==='draft')f.draft.mutate(d=>d.maps.world.name='人工');if(kind==='disabled')f.tools.configure({enabled:false});if(kind==='mode')f.tools.configure({textMode:false});await f.finish();assert.equal(f.store.snapshot().maps.world.currentLocation,'longmen_city');assert.equal(f.draft.snapshot().maps.world.currentLocation,'longmen_city');}finally{f.destroy();}}});
test('manual draft present at generation start is protected; bad batch cannot partially apply',async()=>{const f=fixture();try{f.draft.mutate(d=>d.maps.world.name='人工');f.reply(f.start());await f.finish();assert.match(f.reader.status().message,/人工/);assert.equal(f.draft.snapshot().maps.world.name,'人工');f.draft.discard();f.reply(f.start(),[{op:'move',mapId:'world',id:'qingyun_sect'},{op:'remove_node',mapId:'world',id:'baisha_town'}]);await f.finish();assert.equal(f.draft.status().dirty,false);}finally{f.destroy();}});
test('dry-run does not invalidate active generation; quiet and continuation are ignored; autosave is opt in',async()=>{const f=fixture();try{assert.equal(f.start('quiet'),null);assert.equal(f.start('continue'),null);f.tools.configure({autoSave:true});const data=f.start();f.start('normal',{},true);f.reply(data);await f.finish();assert.equal(f.store.snapshot().maps.world.currentLocation,'qingyun_sect');assert.equal(f.draft.status().dirty,false);f.reader.destroy();assert.equal(f.source.listenerCount('MESSAGE_RECEIVED'),0);}finally{f.destroy();}});
test('expired reply token from a prior generation is rejected',async()=>{const f=fixture();try{const old=f.start();f.start();f.reply(old);await f.finish();assert.equal(f.draft.status().dirty,false);assert.match(f.reader.status().message,/重新查询/);}finally{f.destroy();}});
test('parser accepts one trailing JSON object only',()=>{assert.equal(parseTextUpdate('普通回复'),null);for(const text of ['<map_update>null</map_update>','<map_update>[]</map_update>','<map_update>{}</map_update>后记','<map_update>'+(' '.repeat(50001))+'</map_update>'])assert.throws(()=>parseTextUpdate(text));});
test('worldbook fallback prompt replaces only the owned entry',()=>{const original={entries:{0:{uid:0,content:'保持原样'}}};const create=(name,book)=>book.entries[1]={uid:1};const first=preparePromptBook(original,'a',create,false,TEXT_PROMPT);assert.equal(first.book.entries[1].content,TEXT_PROMPT);assert.deepEqual(first.book.entries[0],original.entries[0]);assert.equal(preparePromptBook(first.book,'a',create,false,TEXT_PROMPT).changed,false);assert.deepEqual(preparePromptBook(first.book,'a',create,true).book,original);});
