import test from 'node:test';
import assert from 'node:assert/strict';
import { createMapTools, compileMapUpdate } from '../src/integrations/tool-calling.js';
import { createDemoDocument } from '../src/core/demo.js';
import { createStore } from '../src/core/store.js';
import { createDraftSession } from '../src/core/draft.js';
import { bindChatStore } from '../src/adapters/chat.js';
function fixture(){
 let ctx={characters:[{avatar:'a'}],characterId:0,getCurrentChatId:()=> 'a',chatMetadata:{},extensionSettings:{},saveMetadata:async()=>{},saveSettingsDebounced(){},registerFunctionTool:t=>registered.set(t.name,t),unregisterFunctionTool:n=>registered.delete(n),isToolCallingSupported:()=>true};
 const registered=new Map(),store=createStore(createDemoDocument()),persistence=bindChatStore(store,{getContext:()=>ctx,storage:{getItem:()=>null,setItem(){}},namespace:'tools'}),draft=createDraftSession(store,persistence),tools=createMapTools({store,draft,persistence,getContext:()=>ctx});
 persistence.importDocument(store.snapshot(),persistence.token());tools.configure({enabled:true});
 return {store,draft,persistence,tools,registered,request:operations=>({token:tools.query().token,reason:'剧情已发生',operations}),switch(){ctx={...ctx,chatMetadata:{},getCurrentChatId:()=> 'b'};persistence.switchChat();persistence.importDocument(store.snapshot(),persistence.token());},destroy(){tools.destroy();draft.destroy();persistence.destroy();}};
}
const move={op:'move',mapId:'world',id:'qingyun_sect'};
test('native tools register, return JSON, stage updates until explicit save and unregister',async()=>{const f=fixture();try{const q=JSON.parse(await f.registered.get('dynamic_map_query').action({}));const r=JSON.parse(await f.registered.get('dynamic_map_update').action({token:q.token,reason:'到达',operations:[move]}));assert.equal(r.applied,false);assert.equal(f.store.snapshot().maps.world.currentLocation,'longmen_city');f.draft.save();assert.equal(f.store.snapshot().maps.world.currentLocation,'qingyun_sect');}finally{f.destroy();}assert.equal(f.registered.size,0);});
test('batch error never partially modifies draft or committed document',()=>{const f=fixture();try{const before=f.draft.snapshot();assert.throws(()=>f.tools.update(f.request([move,{op:'add_edge',mapId:'world',id:'new',from:'missing',to:'qingyun_sect'}])));assert.deepEqual(f.draft.snapshot(),before);assert.equal(f.draft.status().dirty,false);}finally{f.destroy();}});
test('stale tokens, chat switches and replay are rejected',()=>{const f=fixture();try{let r=f.request([move]);f.tools.update(r);assert.throws(()=>f.tools.update(r),/重新查询/);r=f.request([move]);f.switch();assert.throws(()=>f.tools.update(r),/重新查询/);}finally{f.destroy();}});
test('manual drafts are preserved and automatic updates save without lingering conflicts',()=>{const f=fixture();try{f.draft.mutate(d=>d.maps.world.name='人工');assert.throws(()=>f.tools.update(f.request([move])),/人工/);f.draft.discard();f.tools.update(f.request([move]));f.tools.configure({autoSave:true});const r=f.tools.update(f.request([{...move,id:'baisha_town'}]));assert.equal(r.applied,true);assert.equal(f.store.snapshot().maps.world.currentLocation,'baisha_town');assert.equal(f.draft.status().dirty,false);assert.equal(f.draft.status().conflict,false);}finally{f.destroy();}});
test('disabled tools are excluded and execution itself checks enablement',async()=>{const f=fixture();try{f.tools.configure({enabled:false});assert.equal(f.registered.get('dynamic_map_query').shouldRegister(),false);assert.equal(JSON.parse(await f.registered.get('dynamic_map_query').action({})).ok,false);}finally{f.destroy();}});
test('node and road addition uses fixed catalogs, preserves distances and supports all shapes',()=>{for(const type of ['graph','hex','grid']){const d=createDemoDocument();d.maps.world.type=type;const next=compileMapUpdate(d,{token:'t',reason:'新区域',operations:[{op:'add_node',mapId:'world',id:'new',name:'新镇',type:'town'},{op:'add_edge',mapId:'world',id:'new_road',from:'baisha_town',to:'new',distance:50}]});assert.equal(next.maps.world.edges.at(-1).distance,50);assert.equal(next.maps.world.edges.at(-1).name,'');assert.ok(Number.isFinite(next.maps.world.nodes.new.position.x));assert.equal(d.maps.world.nodes.new,undefined);}});
test('deletions are opt in and hidden nodes cannot be queried or mutated',()=>{const f=fixture();try{assert.throws(()=>f.tools.update(f.request([{op:'remove_node',mapId:'world',id:'baisha_town'}])),/未允许/);f.tools.configure({allowDelete:true});f.tools.update(f.request([{op:'remove_node',mapId:'world',id:'baisha_town'}]));assert.equal(f.draft.snapshot().maps.world.edges.length,1);f.draft.discard();f.store.applyUpdate([{type:'upsertNode',node:{...f.store.snapshot().maps.world.nodes.baisha_town,ai:{includeInContext:false,alias:[]}}}]);assert.equal(f.tools.query().map.nodes.some(n=>n.id==='baisha_town'),false);assert.throws(()=>f.tools.update(f.request([{...move,id:'baisha_town'}])),/不可访问/);}finally{f.destroy();}});
test('unknown fields, prototype IDs and invalid type catalogs fail atomically',()=>{for(const op of [{...move,unexpected:true},{op:'add_node',mapId:'world',id:'__proto__',name:'x'},{op:'add_node',mapId:'world',id:'new',name:'x',type:'invented'}])assert.throws(()=>compileMapUpdate(createDemoDocument(),{token:'t',reason:'test',operations:[op]}));});

test('deleting an entrance with a child map is rejected',async()=>{const {createMap}=await import('../src/core/protocol.js');const d=createDemoDocument(),child=createMap('inside','内部','grid');child.parentMap='world';child.metadata.parentNode='qingyun_sect';d.maps.inside=child;assert.throws(()=>compileMapUpdate(d,{token:'t',reason:'删除',operations:[{op:'remove_node',mapId:'world',id:'qingyun_sect'}]},{allowDelete:true}),/子地图/);});
test('native registration failure is optional and cannot break map startup',()=>{const f=fixture();try{const t=createMapTools({store:f.store,draft:f.draft,persistence:f.persistence,getContext:()=>({registerFunctionTool(){throw Error('unsupported');},unregisterFunctionTool(){},extensionSettings:{}})});assert.equal(t.status().registered,false);assert.match(t.status().message,/注册失败/);t.destroy();}finally{f.destroy();}});
