import test from 'node:test';import assert from 'node:assert/strict';
import {preparePromptBook,syncToolPrompt,PROMPT_OWNER,TOOL_PROMPT} from '../src/adapters/tool-lorebook.js';
const create=(_,book)=>{let uid=0;while(Object.hasOwn(book.entries,uid))uid++;return book.entries[uid]={uid};};
const original=()=>({name:'书',entries:{0:{uid:0,comment:'动态地图 · AI 工具使用规则',content:'手动提示'},1:{uid:1,content:''}},extra:{keep:true}});
function fixture(){let book=original(),reads=0,edits=0;const cache=new Map(),ctx={characters:[{avatar:'a.png',data:{extensions:{world:'书'}}}],characterId:0,getCurrentChatId:()=> 'a',chatMetadata:{},getRequestHeaders:()=>({}),saveMetadata:async()=>{}};return{ctx,cache,get book(){return book;},get edits(){return edits;},beforeRead:null,options(){return {getContext:()=>ctx,loadModule:async()=>({createWorldInfoEntry:create,worldInfoCache:cache}),fetcher:async(url,options)=>{const data=JSON.parse(options.body);if(url.endsWith('/get')){reads++;this.beforeRead?.(reads);return {ok:true,json:async()=>structuredClone(book)};}book=structuredClone(data.data);edits++;return {ok:true};}};}};}
test('install, repeat and delete only marked entries; all other content unchanged',()=>{const src=original(),added=preparePromptBook(src,'书',create);assert.equal(added.book.entries[2].content,TOOL_PROMPT);assert.equal(added.book.entries[2].constant,true);assert.deepEqual(added.book.entries[0],src.entries[0]);assert.deepEqual(added.book.entries[1],src.entries[1]);assert.equal(preparePromptBook(added.book,'书',create).changed,false);assert.deepEqual(preparePromptBook(added.book,'书',create,true).book,src);assert.deepEqual(src,original());});
test('server install is idempotent and deletion backs up the owned entry',async()=>{const f=fixture();await syncToolPrompt(f.options());assert.equal(f.edits,1);await syncToolPrompt(f.options());assert.equal(f.edits,1);await syncToolPrompt({...f.options(),remove:true});assert.equal(f.edits,2);assert.deepEqual(f.book,original());assert.equal(f.ctx.chatMetadata.dynamicMapPromptBackups[0].entry.dynamic_map_owner,PROMPT_OWNER);});
test('switching character book during read prevents edits',async()=>{const f=fixture();f.beforeRead=()=>f.ctx.characters[0].data.extensions.world='另一书';await assert.rejects(syncToolPrompt(f.options()),/改变/);assert.equal(f.edits,0);});
test('cache conflicts, concurrent book edits and duplicate markers are rejected',async()=>{const f=fixture();f.cache.set('书',{entries:{}});await assert.rejects(syncToolPrompt(f.options()),/未保存/);assert.equal(f.edits,0);f.cache.clear();f.beforeRead=n=>{if(n===3)f.book.entries[0].content='外部修改';};await assert.rejects(syncToolPrompt(f.options()),/其他操作/);assert.equal(f.edits,0);assert.throws(()=>preparePromptBook({entries:{0:{uid:0,dynamic_map_owner:PROMPT_OWNER},1:{uid:1,dynamic_map_owner:PROMPT_OWNER}}},'书',create,true),/多个/);});
test('no main book and server write failure give explicit errors without changing cache',async()=>{const f=fixture();f.ctx.characters[0].data.extensions.world='';await assert.rejects(syncToolPrompt(f.options()),/未绑定/);f.ctx.characters[0].data.extensions.world='书';const opt=f.options(),fetcher=opt.fetcher;await assert.rejects(syncToolPrompt({...opt,fetcher:(url,o)=>url.endsWith('/edit')?Promise.resolve({ok:false,status:500}):fetcher(url,o)}),/未确认/);assert.equal(f.edits,0);assert.equal(f.cache.size,0);});

